import pymongo
from pymongo import MongoClient
import re


cluster  = MongoClient("mongodb://127.0.0.1:27017/")
db = cluster["signode"]
# c_via = db["via"]
c_vars = db["vars"]

# c_via.insert_one({
#     "Signode_Ship_Via": [
#         "EFIVE LOGIST",
#         "FREIGHTWAY",
#         "Time Sheet",
#         "Air Canada",
#         "Ace Courier",
#         "AM Transport",
#         "Apex Forward",
#         "APPS",
#         "Banstra",
#         "Bus",
#         "Best Way",
#         "Byers",
#         "Cardinal",
#         "Cabano King",
#         "Cdn Frt Ways",
#         "Clark Freightways",
#         "Clarke",
#         "Credit Note",
#         "CN Rail",
#         "Conex Transp",
#         "Canada Post",
#         "Correction",
#         "Consignment",
#         "Comox Valley",
#         "Demark",
#         "DHL Air",
#         "DHL",
#         "Dicom",
#         "Diamond Cour",
#         "Via Download",
#         "Demark North",
#         "Day & Ross",
#         "Dynamex",
#         "Eaglemere",
#         "Fast-A-Flite",
#         "Federal Exp",
#         "Fastfrate",
#         "Forbes Hewlt",
#         "FourPoint Ex",
#         "Gardewine",
#         "Guilbault Tp",
#         "GTO Global",
#         "Goyette",
#         "Hercules",
#         "Invoice Corr",
#         "Ind Breakdwn",
#         "JN Freightwa",
#         "Kingsway Tpt",
#         "Loomis Air",
#         "Loomis Grund",
#         "Mail",
#         "Matson",
#         "Mobile Tspt",
#         "Midland Cour",
#         "Midland Air",
#         "Multifreight",
#         "Midland Tpt",
#         "Maritime Ont",
#         "Moto",
#         "Motopak",
#         "Manitoulin",
#         "Max 24 LTL",
#         "Myers",
#         "Meyers",
#         "Mini-Max",
#         "Natl Fast Ft",
#         "Nimble",
#         "Old Dominion",
#         "Oceanex",
#         "On Site",
#         "Overland Wes",
#         "Puro Air",
#         "Progress Bil",
#         "Purolator",
#         "Pearce Cartg",
#         "Paradise",
#         "Phoenix",
#         "Pineridge Tp",
#         "Pronorth",
#         "Pick Up",
#         "Quik X",
#         "Rebates",
#         "Reimer Exp",
#         "Red Courier",
#         "Rentals",
#         "Robert Tpt",
#         "Routes",
#         "SameDay Grnd",
#         "See Below",
#         "Service Call",
#         "Ser Contract",
#         "SameDay Air",
#         "S&M Trnsport",
#         "Sales Rep",
#         "Unassigned",
#         "TEC Freight",
#         "Thibodeau",
#         "Tiger",
#         "Trans Prov",
#         "Tool Repair",
#         "Trans X",
#         "UPS Air",
#         "UPS",
#         "Vitran",
#         "Vankam Frt",
#         "West Cda Exp",
#         "Yellow"],

#         "_id": "via"
# })

arg = [
    {
    "_id": "glenview",
    "temp_path": "C:\\pickticket_test\\OneDrive - Signode Industrial Group\\Signode Canada Picktickets\\Glenview",
    "email_archive": "\\Picktickets Email Archive\\Glenview",
    },
]

c_vars.insert_many(arg)

print("UPDATED !, externally add Glenview folders in email archive and Signode Canada pick tickets")

